# Generated by Django 4.1.1 on 2023-06-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=128)),
                ('prix', models.FloatField()),
                ('quantite', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='%Y/%m/%d')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionProduit.categorie')),
            ],
        ),
    ]
