# Generated by Django 4.1.1 on 2023-06-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProduit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
